import type { LiraSketch, LiraVariant, LiraExport } from '$lib/types';

// --- WAV export ---

function audioBufferToWav(buffer: AudioBuffer): ArrayBuffer {
	const numChannels = buffer.numberOfChannels;
	const sampleRate = buffer.sampleRate;
	const format = 1; // PCM
	const bitsPerSample = 16;

	const data = new Int16Array(buffer.length * numChannels);
	for (let ch = 0; ch < numChannels; ch++) {
		const channelData = buffer.getChannelData(ch);
		for (let i = 0; i < buffer.length; i++) {
			const sample = Math.max(-1, Math.min(1, channelData[i]));
			data[i * numChannels + ch] = sample < 0 ? sample * 0x8000 : sample * 0x7fff;
		}
	}

	const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
	const blockAlign = numChannels * (bitsPerSample / 8);
	const dataSize = data.length * (bitsPerSample / 8);

	const headerSize = 44;
	const bufferOut = new ArrayBuffer(headerSize + dataSize);
	const view = new DataView(bufferOut);

	function writeStr(offset: number, str: string) {
		for (let i = 0; i < str.length; i++) {
			view.setUint8(offset + i, str.charCodeAt(i));
		}
	}

	writeStr(0, 'RIFF');
	view.setUint32(4, 36 + dataSize, true);
	writeStr(8, 'WAVE');
	writeStr(12, 'fmt ');
	view.setUint32(16, 16, true);
	view.setUint16(20, format, true);
	view.setUint16(22, numChannels, true);
	view.setUint32(24, sampleRate, true);
	view.setUint32(28, byteRate, true);
	view.setUint16(32, blockAlign, true);
	view.setUint16(34, bitsPerSample, true);
	writeStr(36, 'data');
	view.setUint32(40, dataSize, true);

	const int16View = new Int16Array(bufferOut, headerSize);
	int16View.set(data);

	return bufferOut;
}

export function downloadWav(buffer: AudioBuffer, filename: string): void {
	const wavData = audioBufferToWav(buffer);
	const blob = new Blob([wavData], { type: 'audio/wav' });
	downloadBlob(blob, filename);
}

// --- JSON export ---

export function downloadSketchJSON(sketch: LiraSketch): void {
	const json = JSON.stringify(sketch, null, 2);
	const blob = new Blob([json], { type: 'application/json' });
	downloadBlob(blob, `${sketch.name.replace(/\s+/g, '-').toLowerCase()}.json`);
}

// --- ZIP export ---

async function createZipBlob(sketch: LiraSketch, buffer: AudioBuffer): Promise<Blob> {
	// Manual ZIP creation with stored (uncompressed) entries
	const encoder = new TextEncoder();

	const sketchJSON = JSON.stringify(sketch, null, 2);
	const sketchBytes = encoder.encode(sketchJSON);

	const wavBytes = new Uint8Array(audioBufferToWav(buffer));

	const readmeText = `# ${sketch.name}

Generated by Lira — a sound sketchbook.

## Sketch details

- **Name:** ${sketch.name}
- **Duration:** ${sketch.durationSeconds}s
- **Mood:** ${sketch.mood}
- **Material:** ${sketch.material}
- **Shape:** ${sketch.shape}
- **Density:** ${sketch.density}
- **Brightness:** ${sketch.brightness}
- **Softness:** ${sketch.softness}
- **Movement:** ${sketch.movement}
- **Seed:** ${sketch.seed}
- **Created:** ${sketch.createdAt}

Lira is not a DAW. It is a sound sketchbook.
https://github.com/sssuperio/lira
`;
	const readmeBytes = encoder.encode(readmeText);

	const files: { name: string; data: Uint8Array }[] = [
		{ name: 'sketch.json', data: sketchBytes },
		{ name: 'audio.wav', data: wavBytes },
		{ name: 'README.md', data: readmeBytes }
	];

	// Build ZIP
	const chunks: Uint8Array[] = [];
	const centralDir: Uint8Array[] = [];
	let centralOffset = 0;

	for (const file of files) {
		const nameBytes = encoder.encode(file.name);
		const localHeader = new ArrayBuffer(30 + nameBytes.length);
		const lh = new DataView(localHeader);

		lh.setUint32(0, 0x04034b50, true); // local file header signature
		lh.setUint16(4, 20, true); // version needed
		lh.setUint16(6, 0, true); // flags
		lh.setUint16(8, 0, true); // compression: stored
		lh.setUint16(10, 0, true); // mod time
		lh.setUint16(12, 0, true); // mod date
		const crc = crc32(file.data);
		lh.setUint32(14, crc, true);
		lh.setUint32(18, file.data.length, true); // compressed size
		lh.setUint32(22, file.data.length, true); // uncompressed size
		lh.setUint16(26, nameBytes.length, true);
		lh.setUint16(28, 0, true); // extra field length

		chunks.push(new Uint8Array(localHeader), nameBytes, file.data);

		// Central directory entry
		const cdEntry = new ArrayBuffer(46 + nameBytes.length);
		const cd = new DataView(cdEntry);
		cd.setUint32(0, 0x02014b50, true);
		cd.setUint16(4, 20, true); // version made by
		cd.setUint16(6, 20, true); // version needed
		cd.setUint16(8, 0, true); // flags
		cd.setUint16(10, 0, true); // compression
		cd.setUint16(12, 0, true); // mod time
		cd.setUint16(14, 0, true); // mod date
		cd.setUint32(16, crc, true);
		cd.setUint32(20, file.data.length, true);
		cd.setUint32(24, file.data.length, true);
		cd.setUint16(28, nameBytes.length, true);
		cd.setUint16(30, 0, true); // extra field
		cd.setUint16(32, 0, true); // file comment
		cd.setUint16(34, 0, true); // disk number start
		cd.setUint16(36, 0, true); // internal attrs
		cd.setUint32(38, 0, true); // external attrs
		cd.setUint32(42, centralOffset, true);

		centralDir.push(new Uint8Array(cdEntry), nameBytes);
		centralOffset += 30 + nameBytes.length + file.data.length;
	}

	const centralDirBytes = concatUint8Arrays(centralDir);
	const centralDirSize = centralDirBytes.length;

	const eocd = new ArrayBuffer(22);
	const eocdView = new DataView(eocd);
	eocdView.setUint32(0, 0x06054b50, true);
	eocdView.setUint16(4, 0, true); // disk number
	eocdView.setUint16(6, 0, true); // disk with central dir
	eocdView.setUint16(8, files.length, true); // entries on this disk
	eocdView.setUint16(10, files.length, true); // total entries
	eocdView.setUint32(12, centralDirSize, true);
	eocdView.setUint32(16, centralOffset, true);
	eocdView.setUint16(20, 0, true); // comment length

	chunks.push(centralDirBytes, new Uint8Array(eocd));

	return new Blob([concatUint8Arrays(chunks)], { type: 'application/zip' });
}

function crc32(data: Uint8Array): number {
	let crc = 0xffffffff;
	for (let i = 0; i < data.length; i++) {
		crc ^= data[i];
		for (let j = 0; j < 8; j++) {
			if (crc & 1) {
				crc = (crc >>> 1) ^ 0xedb88320;
			} else {
				crc = crc >>> 1;
			}
		}
	}
	return (crc ^ 0xffffffff) >>> 0;
}

function concatUint8Arrays(arrays: Uint8Array[]): Uint8Array {
	const total = arrays.reduce((sum, a) => sum + a.length, 0);
	const out = new Uint8Array(total);
	let offset = 0;
	for (const a of arrays) {
		out.set(a, offset);
		offset += a.length;
	}
	return out;
}

export async function downloadZip(sketch: LiraSketch, buffer: AudioBuffer): Promise<void> {
	const blob = await createZipBlob(sketch, buffer);
	downloadBlob(blob, `${sketch.name.replace(/\s+/g, '-').toLowerCase()}.zip`);
}

// --- Utility ---

function downloadBlob(blob: Blob, filename: string): void {
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}

export function makeExportRecord(
	sketch: LiraSketch,
	filename: string,
	format: 'wav' | 'json' | 'zip',
	durationSeconds: number,
	sampleRate: number,
	variantId?: string
): LiraExport {
	return {
		schema: 'lira.export.v1',
		id: `exp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
		sketchId: sketch.id,
		variantId,
		filename,
		format,
		createdAt: new Date().toISOString(),
		durationSeconds,
		sampleRate
	};
}
